# Generated by Django 4.2.1 on 2023-06-03 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tab', '0002_tab_created_at_tab_description_belonging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belonging',
            name='tab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tab.tab'),
        ),
        migrations.AlterField(
            model_name='belonging',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
