# Generated by Django 4.2.1 on 2023-06-03 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tab', '0003_alter_belonging_tab_alter_belonging_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belonging',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.tab'),
        ),
        migrations.AlterField(
            model_name='belonging',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='belonging',
            unique_together={('user', 'tab')},
        ),
    ]
