# Generated by Django 4.2.1 on 2023-06-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0004_alter_belonging_tab_alter_belonging_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('isPrivate', models.BooleanField(default=True)),
                ('tab', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.tab')),
            ],
        ),
    ]
