# Generated by Django 4.2.1 on 2023-06-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0005_expensetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensetype',
            old_name='isPrivate',
            new_name='is_private',
        ),
        migrations.AddConstraint(
            model_name='expensetype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_private', False), ('tab__isnull', True)), models.Q(('is_private', True), ('tab__isnull', False)), _connector='OR'), name='is_private_no_tab'),
        ),
    ]
