# Generated by Django 4.2.1 on 2023-06-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_rename_isprivate_expensetype_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='tab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.tab'),
        ),
    ]
