# Generated by Django 4.2.1 on 2023-06-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0007_alter_expensetype_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.tab'),
        ),
    ]
