# Generated by Django 4.2.1 on 2023-06-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0008_alter_expensetype_tab'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensetype',
            unique_together={('name', 'tab')},
        ),
    ]
