# Generated by Django 4.2.1 on 2023-06-03 20:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tab', '0009_alter_expensetype_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 6, 3, 22, 14, 52, 481394))),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tab.tab')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tab.expensetype')),
            ],
        ),
    ]
