# Generated by Django 4.2.1 on 2023-06-03 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0011_alter_expense_date_associating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 23, 14, 23, 57929)),
        ),
    ]
