# Generated by Django 4.2.1 on 2023-06-13 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0016_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='belonging',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 18, 1, 21, 727586)),
        ),
    ]
