# Generated by Django 4.2.1 on 2023-06-14 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0017_belonging_is_active_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 20, 47, 56, 567831)),
        ),
    ]
